### ISSUE TITLE
Include Reference to Open Source license in the script

### ISSUE THREAD

**Issue by MikeZahorik** [Id-Extras/Snap-Margins-to-Text-Frame#1]
Hi, 
Please place a reference to the MIT Open Source license in the script too. End users may download the script directly without seeing the folder in GitHub so insert that into the script too. 
Thanks,
Mike

**Comment by Id-Extras** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Hi Mike,
    Do you have an example of a 1-line blurb that would do this
      effectively, or should I just copy the entire license text to the
      beginning of the script?
    Ariel
    
    
      T.A. Walden | Bookraft LLC
www.Id-Extras.com
      
      
    
    On 04/06/2020 22:48, Mike Zahorik
      wrote:
    
    
      
      Hi,
        Please place a reference to the MIT Open Source license in the
        script too. End users may download the script directly without
        seeing the folder in GitHub so insert that into the script too.
        Thanks,
        Mike
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Id-Extras/Snap-Margins-to-Text-Frame/issues/1",
"url": "https://github.com/Id-Extras/Snap-Margins-to-Text-Frame/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MikeZahorik** [comment]
I don't have an example. The MIT license is short enough to stick it all in there, maybe link back to the license file in your repository otherwise.
